development:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: ENV["EMAIL_USER_NAME"]
  :password: ENV["EMAIL_PASSWORD"]
  :enable_starttls_auto: true
production:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: xxx
  :password: yyy
  :enable_starttls_auto: true